### ISSUE TITLE
[BUG] Backspace occasionally deletes spaces that don't immediately preceed the cursor

### ISSUE THREAD

**Issue by nextcloud486153** [TechbeeAT/jtxBoard#1021]
**Describe the bug**
I'm seeing the exact same behaviour shown in #160.

I'm using OpenBoard, which seems to be based off AOSP Keyboard, but I have been using it for years in multiple apps with similar Markdown-writing aids and have experienced no problem.

The fix proposed in #160 doesn't work for me, as I don't have another keyboard that satisfies my needs to replace OpenBoard. Perhaps a toggle could be provided in the app's settings to disable Markdown writing aids (which seem to be the source of the problem in the discussion on #160).

**To Reproduce**

1. Install OpenBoard or AOSP keyboard and set it as the default input method.
2. Open JTX and write something in the description field.
3. Press backspace, the first character behind the cursor is erased.
4. The first space behind the cursor (not immediately behind it) gets erased, forcing moving the cursor to re-insert the space.

**Expected behavior**
(3) should not happen.

**Screenshots**
The video in #160 illustrates my exact issue. I could provide additional video, but it would be almost a copy of the one already provided.

**Device and version**
 - Device: Huawei P20 Lite
 - Android version: Android 9
 - jtx Board version: 2.06.03.ose (206030001)
 - Downloaded from: F-Droid
 - Keyboard version: OpenBoard 1.4.5 (installed from [F-Droid](https://f-droid.org/es/packages/org.dslul.openboard.inputmethod.latin/))

**Comment by patrickunterwegs** [comment]
Hi @nextcloud486153 , 
as you already mention, also in #160 there was not really a solution... I am updating the libraries regularly, but obviously this is still not completely solved. From the code perspective it's still a standard text field, just with that bit of support when markdown is enabled. 
You can already disable markdown in the top right menu when you edit an entry (you can basically enable/disable markdown for journals, notes and tasks independently and just activate or deaktivate it as you need it). So you can try this, I'm not sure if it will solve the problem though...

**Comment by nextcloud486153** [comment]
Could you point me to the library/configuration of the text fields, so I can test the text fields and see if I can file a reproducible bug report either to OpenBoard or to that library?

**Comment by patrickunterwegs** [comment]
> Could you point me to the library/configuration of the text fields, so I can test the text fields and see if I can file a reproducible bug report either to OpenBoard or to that library?

Hi @nextcloud486153 , sure, so this is the line where the TextField is set: 
https://github.com/TechbeeAT/jtxBoard/blob/0e9cd1a667f46be35c1d43e9f8943f3e72bdbcab/app/src/main/java/at/techbee/jtx/ui/detail/DetailScreenContent.kt#L534

jtx Board uses here the OutlinedTextField, which is a standard component within the Material 3 components (which is the newest UI-component library) provided by Google: https://m3.material.io/components/text-fields/overview

The important thing here is that jtx Board uses the jetpack compose UI-framework (which is the newest one) instead of older XML layouts, which might not have this problem. 

I believe that the problem occurs with this combination of jetpack compose and Material 3. As many other apps might still use older XML layouts or older Material UI components, users might only see this issue in a few apps that are really up to date and use the latest libraries and components.

**Comment by rogercreagh** [comment]
@patrickunterwegs  Er, why is this (and #160 ) closed - it still happens and it is still a bug from the user's point of view. It only happens in jtxB (for me at least), the same keyboard (Open Board in my case) does not show the problem with any other app including google own ones.

If the problem is that jtxB is using components that are causing the bug in their latest versions then shouldn't you simply downgrade to the older versions that do work correctly until the components are fixed.

Sometimes being on the bleeding edge is a bleeding nuisance ;-)

**Comment by patrickunterwegs** [comment]
Well, I explained before why it might happen with jtx Board and not with other apps that probably use older frameworks or other libraries. 

If downgrading the library would change anything, I'd do it. But I don't think it ever worked properly with Open Board. But the fact that it is just a standard component and that it only seems to occur with certain keyboard providers makes it pretty obvious that it's related to the keyboard itself. 

There is really no point in changing anything on jtx Board side. So you should better address this with your keyboard provider...

**Comment by Julianoe** [comment]
From what I can read it's not a bug that only happens to people using pretty old devices (mine is stuck in Android 7), so there's not even that reason.

I have the same problem with Android 7, Android default keyboard.

I'm not sure to understand the answer. It only happens in jtx Board (I use dozens of apps, lot of em where the main pruprose is to type text), but it's a can't fix on jtx Board side, which is the only app where this happens? Where do we need to report the bug then?

Typing text is the main purpose of the app and this is a bug affecting this. One could hope we are just a few ones experiencing it but if it happens on default android keyboard and on version up to Android 13 it means the main feature of the app has a bug for most of the users.

How can we work towards fixing this?


For the record here are issues that describe exactly the same problem:
- on LineageOS gitlab: https://gitlab.com/LineageOS/issues/android/-/issues/4429
- on the Google issuetracker: https://issuetracker.google.com/issues/294102838

**Comment by rogercreagh** [comment]
I think it is a quirk of the editor I'm using (OpenBoard) and not the Android version (11)

Having said that it did get better for a while but now seems to have come back with a vengeance - no idea why that might be. Started recurring for me around 2 releases ago.

**Comment by Julianoe** [comment]
That's really strange. I don't know how it was before because I just discovered the app recently (and it covers some of my use cases perfectly, so, thank you for that), but I have this bug consistently, every time I edit text in it :(

**Comment by patrickunterwegs** [comment]
Hi, sorry that this issue got worse again. 
But as stated before, it's almost impossible to do something about it in the app itself. 

@rogercreagh , I'm regular updating the compose-version (compose is the UI framework). If you say it just re-appeared, I guess it was because of such an update. I could set it back, but I would just prefer to always stay with the latest version...

@Julianoe I understand the frustration, but as you pointed out already, the issue has already been addressed multiple times on Google side. It's just a basic text field where text should be entered. Google doesn't seem to be capable to find a proper solution for this issue. But regrettably I also don't see a workaround or anything that I could do...

**Comment by Julianoe** [comment]
@patrickunterwegs I feel that your answer describes the workaround in itself: what's the benefit of updating compose to the latest version other than staying updated to the latest version? If the bug comes and goes why not jump from one that works to another one that works too? If it's indeed just a Text field it will probably tolerate to not be updated to the upmost recent version every single time. Maybe?

About Google: at this point I think we have all understood that it's a giant of Rhodes... that name is not a seal of quality and reliability, this example is just another instance. Regrettable that we have to deal with this.

**Comment by patrickunterwegs** [comment]
@Julianoe I will downgrade for now. But it's not a sustainable solution. What happens when another version gets released that might fix the issue for good? Then I should have upgraded... Or make it worse? Then I should have stayed... I can't even tell myself because  I can't even reproduce the issue...

**Comment by rogercreagh** [comment]
What I find most puzzling is that jtxB is the only app I use that exhibits this behaviour. Other apps that I use a lot and have text entry include FairEmail, NextCloud Deck, WhatsApp, Signal, Telegram, Substack, Edge (eg when entering text on web forms like this one, or editing text in a CMS admin role) - I've never had the problem on any of those.

**Comment by patrickunterwegs** [comment]
@rogercreagh The thing is that most other apps might still use (older) XML layouts while jtx Board uses the more modern UI-framework Jetpack Compose. This is anyway the one that is promoted by Google and that will be the future, so once older apps get refactored (which is a lot of work, as this can't just be migrated), also those other apps will have the same problem.

**Comment by Julianoe** [comment]
After 2 weeks of daily usage: I can say that whatever is the reason this is a valid reason not to use this app. Every text entry is a huge pain to type. And as this is the main objective of the app, it's really a problem.

**Comment by joao-matos** [comment]
Anyone with this issue and likes openboard, I can confirm the bug is not present in Heliboard, an OpenBoard fork
https://f-droid.org/packages/helium314.keyboard

**Comment by rogercreagh** [comment]
It still happens to me but I've learnt to live with it by not typing backspace delete too rapidly. It (openboard presumably) needs time to think about what to do after each backspace. I don't want to ditch either jtxB (there is no alternative) or Openboard (simply the best tablet/phone keyboard layout there is) - I'll have a look at Heliboard and try that is it hasn't broken or bloated the underlying openboard. Thanks @joao-matos

**Comment by Julianoe** [comment]
The default Android keyboard still has the bug for me.
Installed Heliboard and I did not have the bug. Thanks for mentioning it @joao-matos .
Still don't understand why this is the only app with this problem though.
