### ISSUE TITLE
[Feature] jtxBoard-side settings for synchronised collections

### ISSUE THREAD

**Issue by nazarewk** [TechbeeAT/jtxBoard#1037]
**Is your feature request related to a problem? Please describe.**

I have created dedicated jtx Board collection in Nextcloud, but it still creates entries with Personal collection selected by default and I have to manually change it.

**Describe the solution you'd like**

It would be nice to also be able for DAVx5 (or any other) collections to be:
- selected as a default for entry type (note/journal/task)
- toggled on/off just for jtxBoard
- marked as read-only just for jtxBoard

**Describe alternatives you've considered**

Going through settings I found no way to achieve it.

EDIT: actually seems like the last selected collection is remembered which solves my primary annoyance, but I didn't know about it. It would be useful to have a separate "last used" default entry (in addition to all present collections).

**Additional context**

**Comment by patrickunterwegs** [comment]
Hi @nazarewk , 
thank you for your remarks. 

> selected as a default for entry type (note/journal/task)

As you noted correctly, the last used collection is saved. I don't see the need for a setting to define a default collection, this would then also contradict with the currently last used collection. But alternatively you can use the top bar and set it to add a new entry instead of search. There you can set a collection explicitly.

> toggled on/off just for jtxBoard
> marked as read-only just for jtxBoard

I have had a look at such a request before, but I don't see why jtx Board should handle this. Showing/hiding collections can also be achieved through the filters. If a user doesn't want to see a specific collection at all, what would be the point in having the data there and even causing resource usage by synchronising entries that are not even visible? This should be a request towards DAVx5.
The same for marking a collection as read only within jtx Board. I am also keeping in mind that you can use collections without sync where such a read-only option would make not much sense. 
On the other hand DAVx5 can set a collection already as read-only (either by setting it in the UI or because the server-collection is read-only). So I understand that you might want to have the collection in jtx Board as read-only while the calendar within the collection can be edited by other applications - but I would see this again within DAVx5 and not jtx Board.

**Comment by rogercreagh** [comment]
Oh, shame I missed this one @patrickunterwegs  I would endorse @nazarewk 's first request. I'd prefer to have a default collection than the last used collection. I have about four collections (5 including a test one that I rarely use), one that I use every day and the others once or twice a week or less.

Every time I add something to one of the minor journals I forget that I did that the next day when I go to add an entry to the daily journal and it ends up in the wrong collection. Very annoying. Sometimes I don't notice for 3 or 4 days and have to go back and edit all the entries that were made in the wrong journal.

When you start a new entry your (my) focus tends to be on what I'm going to write so I forget to check the collection is correct. It would possibly work better if the collection selector appeared after the description field and above the categories. 

Yes I know the collection labels can have a coloured label, but on a greyscale screen it is not always obvious that the label is a wrong shade of grey, and the text is pretty small (this is not a request to make it bigger)

If you really don't want to consider the option of having a default journal as an alternative to the last used one (it would only be a simple setting with "last used" as a selectable option along with the collection names) then how about having it so that if a filter by collection is active then that collection becomes the default. If I am adding to a less used collection I often start by filtering the list by the collection to see what I last wrote.
