### ISSUE TITLE
[Feature] When using the calendar, show border around dates containing journals

### ISSUE THREAD

**Issue by Kiwzi** [TechbeeAT/jtxBoard#1104]
**Is your feature request related to a problem? Please describe.**
Not a "problem" per say, but more like a missing "convenience"

**Describe the solution you'd like**
When searching for journals using the calendar it would be more convenient if there was some kind of "mark" on dates containing journals.

**Describe alternatives you've considered**
Not considered any alternatives.

**Additional context**
Current date: no change.
Selected date: no change.
Dates with entries: border, white number, no background.

Screenshot is my proposal to this feature:
![Screenshot_20231230-104148_jtxBoard](https://github.com/TechbeeAT/jtxBoard/assets/143224712/f48d7284-2d46-489e-8810-e22fad7ac6ff)

**Comment by Kiwzi** [comment]
Also, if possible, after selecting a date, hide all other journals and not only scroll down to selected date.
I feel like when I choose a date, that is the date I want to see journals from, not any other dates, if that makes sence :)

**Comment by patrickunterwegs** [comment]
Hey @Kiwzi ! Thank you for your proposal! :-)
Basically we are talking about two different things here: 
- Use a date-picker to scroll to a specific date
- Select a date or date range to filter elements within the range

The first one is more like a legacy thing that I implemented a long time ago and just kept. It's not that useful because it is only possible to use when you sort by date.
The second one is already possible in the filter options (Date ... - ...). 

Now I understand that it might be helpful to mark dates that actually have elements. 
But for the second part to actually filter the entries, I'm not sure if this adds so much value. If you select e.g. a month in this date range filter, would it change something if you knew that there are entries for that day?

What technically could be achieved easily is to only enable dates that have entries for the scroll-to-date functionality. Do you think that would help?

**Comment by Kiwzi** [comment]
I agree that this has little value for the range filter.
But for the "scroll-to-date" to behave more like a "pick-a-date" so I can quickly see a spesific date (nothing more) would be awesome.
So if I understand you correctly, when you say "enable dates that have entries", that mean dates without entries are just greyed out but still visible, then I agree to what you think.

**Comment by patrickunterwegs** [comment]
> So if I understand you correctly, when you say "enable dates that have entries", that mean dates without entries are just greyed out but still visible, then I agree to what you think.

Exactly. I just did it, I'll release the 2.7.0-beta soon, I'd appreciate if you could also test it a bit and give feedback :-)

**Comment by patrickunterwegs** [comment]
Done in #1135

**Comment by Kiwzi** [comment]
@patrickunterwegs This works perfectly, thanks for implementing it :)
