### ISSUE TITLE
[BUG] jtx Board crashes in the background (Android 9, 10, 11)

### ISSUE THREAD

**Issue by burningT** [TechbeeAT/jtxBoard#117]
**Describe the bug**
The latest update seems to lead to repeated crashes of the app. Android reports periodically at about every minute a repeated closing of the app. 

**To Reproduce**
No in app activity required. The Android message even pops up while writing this text. Additionally, the message seems to be triggered by opening the app.

**Expected behavior**
No Android message

**Screenshots**
![Screenshot_20230101-135421_Ecosia](https://user-images.githubusercontent.com/5808054/210171251-4ea501ff-a53c-4b72-a085-44770c26ea78.png)

**Device and version:**
 - Device: SHIFT6mq
 - jtx Board version: 2.01.07.rc03-gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hey @burningT !
Thank you for the bug report and sorry for the issue.
It's a problem that only occurs in Android 9, 10 and 11, that's why it wasn't going while testing.
The new version that will hopefully fix this issue for good is waiting for approval at Google and should come within the next hours!
Cheers, Patrick

**Comment by patrickunterwegs** [comment]
Hey @burningT , the update is now live, could you update, try again and give some feedback if it's solved also for you?

**Comment by burningT** [comment]
Hi Patrick,
 
unfortunately the behavior persists with rc04. Nothing seems to have changed here even after reboot.
 
Von: Patrick Lang ***@***.***> 
Gesendet: Sonntag, 1. Januar 2023 15:59
An: TechbeeAT/jtxBoard ***@***.***>
Cc: burningT ***@***.***>; Mention ***@***.***>
Betreff: Re: [TechbeeAT/jtxBoard] [BUG] jtx Board crashes in the background (Android 9, 10, 11) (Issue #117)
 
Hey @burningT <https://github.com/burningT>  , the update is now live, could you update, try again and give some feedback if it's solved also for you?

**Comment by patrickunterwegs** [comment]
Hey @burningT , sorry to hear :-( That issue is also kind of hard to reproduce...
During my tests everything just seemed fine, also with Android 10. Which Android version are you using?
Have you opened the app once after the update without any issues? 
May I ask you to make a new entry for a widget and see if the issue is still there?
If yes, would you mind removing the widget and adding it again to the Home Screen?

Thanks, Patrick

**Comment by burningT** [comment]
Hi Patrick,

Thank you for your immediate reaction here.

I am running Android 10 indeed (SHIFT6MQ.SOS.3.8.G.20220824).

After updating to rc03 I could open the app successfully at least once. There seems to be absolutely no way of repeating that now.

Unfortunately there seems no way of doing anything by widget as well. When I add the widget to some screen, it immediately disappears. I also observed it getting stuck above all other displays before disappearing.


Am 1. Januar 2023 16:11:08 MEZ schrieb Patrick Lang ***@***.***>:

**Comment by patrickunterwegs** [comment]
Hey @burningT another fixing update was just approved by Google, may I ask you to try again?

**Comment by burningT** [comment]
Hi Patrick, 

Your dedication is magnificent. Also, your fix seems to work now. Good job. Happy new year :-)

Am 1. Januar 2023 20:11:11 MEZ schrieb Patrick Lang ***@***.***>:

**Comment by patrickunterwegs** [comment]
Thanks for the update, I'm glad it works now :-)
Happy new year to you as well :-)

**Comment by patrickunterwegs** [comment]
Done in 96b49c82bb36c99a201d40e7109d6566aac5951c
