### ISSUE TITLE
[Feature] make sync on app start the default [ose]

### ISSUE THREAD

**Issue by basings** [TechbeeAT/jtxBoard#1202]
**Is your feature request related to a problem? Please describe.**

The app does not sync automatically on app start by default which can be confusing if you expect a seamless behavior. Many people do not inspect the settings thoroughly. Hence, they are unaware that it's simply not automatically syncing because of the setting.

**Describe the solution you'd like**

Make syncing on app start the default.

In #441 it's stated that people complain about unneccessary syncs in e.g. #576 which lead to disabling sync on app start #938 . 

In my opinion this is very unlucky. I understand the reasoning behind it but many users use "public" servers. There is no visible indication that there was no sync happening but there is a notification that sync didn't work. Meaning, as a user who does not check the settings thoroughly (it's almost the last toggle) you are left with an unsyncing app. Thus, the initial behavior should be a working state and if an error/ warning occurs, people shall have a look into the solution.

**Your current device and version**
 - Device: Pixel 6 GrapheneOS
 - Android version: A13
 - jtx Board version: 2.07.00.ose (207000009
 - Downloaded from: github / obtainium

**Comment by patrickunterwegs** [comment]
Hi @basings , 
well, the question is what is the lesser of two evils - user complaining about automatically triggered syncs on app start or users complaining about a missing sync on app start (until both find the setting).
The problem was additionally that users had some performance issues when the sync was running and this was especially bothering when it happened directly on app start. 
"... you are left with an unsyncing app" - this is not correct. DAVx5 still has sync intervals that would regularly do the sync anyway (unless you consciously turn them off). Additionally on every change of an entry the sync framework would be notified and trigger a sync after a while.

What I could imagine is to enable the sync on start by default for users with newer devices (like Android 13+, expecting that they would have devices with good performance).
