### ISSUE TITLE
[Feature] Priority overhaul

### ISSUE THREAD

**Issue by taykuctd** [TechbeeAT/jtxBoard#1319]
Good afternoon, greetings from Poland!

First, I want to thank you for your amazing work on jtx Board. It is helping me managing my neurodivergent brain tremendously, making my life easier. Since I am using F-Droid version, I will donate in the future.

I would like to open a discussion regarding priorities in Tasks, and how they are communicated to an user. In the current state, I feel like priorities are just a thing you can use for sorting/ordering, and they serve no other purpose than that. They are really challenging to guess at first sight.

Disclaimer: I am in no way expecting those to be developed, as it is a hard work maintaining such an app by itself, and I am demanding nothing. I just love the app and would like to communicate on how to improve it.

Current issues I've noticed: 
1. Priorities are buried under attributes such as categories, and there is no way for me to quickly see the priority without going into the actual task.
![Screenshot_20240409-153129~2](https://github.com/TechbeeAT/jtxBoard/assets/137068576/e9f66447-c00c-4662-a73b-87250e882852)

Solution: re-work the UI to always show the priority.

2. Priorities have no proprieties on their own, meaning they are not customizable. For example, I am not able to select a color or order for a particular priority. 

Solution: Allow user to customize priorities: peg a particular color to a priority level, so the task will be highlighted automatically.

3. Priority scale of 1-10 is a bit too much for my liking, and I don't use anything else than "High", "Medium", or "Low", except for testing. Previously I've used Tasks.org, and 3 levels of priorities "Red" "Yellow" and "Blue" were just right for my use case. Also, they were tied to a color, so I was able to distinguish high priority tasks on a first glance.

Solution: allow user to alter the priorities; implement alternative prioritization level and methods. 

4. Priorities are not visible on a widget, or I couldn't figure on how to display them. 

Solution: show priorities on a widget by default.

5. Priority levels on a Task view are always purple, which is another difficulty to distinguish between them. 

Solution: make priorities pop! :-)

Hope that helps. Once again, thank you for your magnificent work!

**Comment by taykuctd** [comment]
Also, I've got an idea about priorities. Colors could indicate how high the priority is. The color would be drawn by the left of the Task entry like follows:
![Screenshot_20240409-153129~3](https://github.com/TechbeeAT/jtxBoard/assets/137068576/d19758bf-c11f-43ff-8e1b-b841eebdf977)

**Comment by patrickunterwegs** [comment]
Hi @prkuctd !
Thank you for your proposals! :-)

There's a few things to say about them: 
Basically the numbers for priorities come from the iCalendar standard (RFC-5545). I just wanted to provide the full support, even if it might seem too much. And you're right, currently it's mainly an attribute you can set the sort order for.

What I could do about the place in the list is to move it after the due date and before the categories, this way it will be more likely that the priority gets fully visible. By the way you can scroll this bar to see all the rest 😉 

I can also add the priority to the widget. There I would rather only show the number to save some space. 

About customizable priorities: I really don't want to add something like that, also about the color I'm very hesitant. 
If users need specific priorities, I would rather recommend to use categories. You can also go to the presets screen and set a color to a category and just use this instead. 

Also highlighting the entry based on the priority is a bit too much for me. The problem is that the collection already can have a color, the entry itself can have a color, the overdue badge has a different color and the categories can have a different color. I'm afraid it's just getting too much if another coloring option is provided. 

Anyway, I'm also open for discussion 😉

**Comment by taykuctd** [comment]
Thank you so much for your reply @patrickunterwegs. You're right, additional coloring schemes would clutter the app. So, I propose to include an option for "sticky" or "frozen" priorities - enabling it would ensure priority is a first thing after due date, and can't be buried by other task attributes. Also, maybe implementing showing priority on widgets would be a good idea?

Once again, I'm really grateful for the app. Have a lovely day :)

**Comment by patrickunterwegs** [comment]
Thanks @prkuctd ! I have prepared the mentioned two changes and I'll merge them soon in the codebase to provide a new version =)
(You can follow #1296 if you're interested).
Have a good weekend! =)
