### ISSUE TITLE
[Feature] less deletion options

### ISSUE THREAD

**Issue by cptsanifair** [TechbeeAT/jtxBoard#1336]
**Is your feature request related to a problem? Please describe.**

Deletion everywhere... I use tasks, calendar and co to create a history.

For me its a trap if i get all over the app as first offert to delete my done work

**Describe the solution you'd like**

reduce the count of ways to "delete all done work" 

**Describe alternatives you've considered**

Add an option to edit the menue points, or add a switch to unshow the "delete all done work" buttons.

**Comment by patrickunterwegs** [comment]
Hi @cptsanifair !

> reduce the count of ways to "delete all done work"

I don't really see the actual problem here. The delete all done tasks option is only in ONE place, it is not obvious but hidden behind the three dots. Even when you click on it, the app would warn you with a dialog where you have to confirm. I think there's no way that a user accidentally clicks on the three dots, on the delete all and then accidentally confirms with "Delete".
