### ISSUE TITLE
[BUG] When you're creating/editing a journal's description, no save button appears

### ISSUE THREAD

**Issue by TalOrenshtein** [TechbeeAT/jtxBoard#134]
**Describe the bug**
When you're creating/editing a journal's description, no save button appears.

**To Reproduce**
1. Create or edit a journal.
2. Edit the description.
3. Try to save.

**Expected behavior**
Being able to save with the save button.

**Device and version:**]
 - jtx Board version:   2.01.07-rc05.ose
 - Downloaded from: f-droid

**Comment by patrickunterwegs** [comment]
Hey @TalOrenshtein !
The problem is actually the space. When you have markdown enabled, the bottom bar turns into the markdown bar that you can collapse again on the bottom left. 

I'm still not sure what's the best compromise between using the space for markdown and the general actions...

**Comment by TalOrenshtein** [comment]
You can move the save button to the top. Near the 3 dots for example.

**Comment by rogercreagh** [comment]
It did confuse me the first time the markdown toolbar appeared when entering a text box, but I find the left arrow at the left end of the toolbar to bring back save, back, trash and settings works fine.

I prefer the save button where it is.

If you are not using markdown you can turn it off in the details or edit view on the three dots menu at the top and then the save doesn't shuffle off when editing text.

**Comment by patrickunterwegs** [comment]
I agree with @rogercreagh , the save button should not move to another position. This is also an important design idea that the most important action is in the same place on the screen and easily reachable by the thumbs.

I will take this issue to experiment again with the save button being visible also on the markdown bar. I did this already before, but I was struggling a lot with Google's Implementation of the bottom bar and the floating action button so that I went with the curre t solution. But maybe I can find a better way again.

**Comment by patrickunterwegs** [comment]
Alright, so I'll keep the save button visible now, it will look like that: 

![Screenshot_1673536916](https://user-images.githubusercontent.com/72232737/212109221-c4f11e12-58b3-429f-a351-ce62e5cde45f.png)

I'm not super happy with the solution as I am using fractions. I've tried it on a phone and on a tablet and both looked nice. But especially on smaller phone screens of different sizes this could end up in a strange UI. So I am still confident, that the solution will fit for most devices. 🙂
