### ISSUE TITLE
[Feature] Add QS tiles

### ISSUE THREAD

**Issue by BLACK4585** [TechbeeAT/jtxBoard#1374]
**Is your feature request related to a problem? Please describe.**
When I just want to create a simple task, reminder or so, I have to go into the app and create a task and do all the required things.

**Describe the solution you'd like**
It would be nice to have QS tiles which you can press to instantly create a note, journal, task etc.

**Describe alternatives you've considered**
Opening the app manually.

**Comment by patrickunterwegs** [comment]
Hi @BLACK4585 
So you have any app that I could look at to see how others solved that?

**Comment by BLACK4585** [comment]
Not directly. But I suggest three simple tiles for the beginning. One for creating a journal, note, and task each. I think this would greatly improve the usability of the app regarding creating quick notes or tasks.

**Comment by patrickunterwegs** [comment]
Hi @BLACK4585 , 
I have checked the tiles option, but I think it doesn't make much sense here.

Tiles are more used to change settings. There is an option to open a dialog from tiles, but still it doesn't add any value. 

You can already use quick actions from the app icon just by long tapping on it. Those quick actions you can also move to your home screen. So at the end this is even faster than using tiles: 

![Screenshot_20240429_224207_Microsoft Launcher.jpg](https://github.com/TechbeeAT/jtxBoard/assets/72232737/24d1d8ea-6147-4aa6-abd6-212b71fb2564)

**Comment by BLACK4585** [comment]
I have now found some examples. 
Ruppu uses a tile to create a new entry, Shazam to instantly recognize songs, Bitwarden to jump to the vault or password generator instantly, Nextcloud Notes to create a new note and Image Toolbox to access certain features directly. Also Home assistant gives you 10 free choosable tiles you can use to e.g. start automations.
Maybe you want to reconsider adding such tiles, would be glad.

**Comment by patrickunterwegs** [comment]
Thanks @BLACK4585 !
I have checked Ruppu and Nextcloud Notes. 
Nextcloud Notes even crashed on tapping on the tile. 
Ruppu has a tile, but just opens the app with the option to add a new entry. That's more or less exactly what jtx Board does when you start a new entry from the widget or when you use the quick actions as I described before. The quick actions are even better, because they make clear if you'd like to create a journal, note or task.

I'm sorry, but I don't see any advantage here in using tiles.
