### ISSUE TITLE
[BUG] purchasing pro version on grapheneos

### ISSUE THREAD

**Issue by marimes** [TechbeeAT/jtxBoard#1406]
**Describe the bug**
I don't seem to be able to purchase the pro version. It is perhaps related with me using graphene os and lacking the google play services.

**To Reproduce**

1. Select "Pro kaufen" from the burger menu
2. Click on "Upgrade auf jtx Board Pro"

Now I get the message "Bitte überprüfen Sie Ihre Internetverbindung und probieren..."

**Expected behavior**
Method to purchase and install the pro features.

**Screenshots**

**Device and version**
 - Device: Pixel 8 Pro
 - Android version: 14, build no 2024050700
 - jtx Board version: 2.07.06.gplay (207060004)
 - Downloaded from: f-Droid, ...

**Comment by patrickunterwegs** [comment]
Hi @marimes ,

I don't know why this aurora store takes apps with in app purchases at all as they are not supported as Google Play services are missing on Graphene OS... So that's the actual problem. In your case please take the version from f-Droid which is 98% the same as the Google Play version (there's a difference mainly for location based services which require Google libraries)!

Regards, 
Patrick
