### ISSUE TITLE
[BUG]  Upgrade while jtxBoard was running results in not starting/crashing.

### ISSUE THREAD

**Issue by afc54** [TechbeeAT/jtxBoard#1428]
**Describe the bug**
Ran F-droid to upgrade jtx Board since I had a notification that a new version was ready to install.  Realized too late that jtx Board was running, doing a sync with my local  radicale server after I had tapped to install the new version.  After this, running jtx Board never starts: "jtx Board has stopped Restart app".  When I restart the same message appears, restarting again comes up with "jtx Board keeps stopping Close app".  When closing  that pop-up disappears but trying to restart jtx Board results in the same loop, over and over, even after uninstalling and reinstalling.  Since uninstall/reinstall is not sufficient to clear up the problem, is there another more radical way to uninstall or reset partially installed data?

**To Reproduce**
Upgrade to a newer version while jtx Board is syncing to a local radicale server.

**Expected behavior**
That it would either wait until the sync is complete and then upgrade or that it would give an error message that it's syncing and try to install the upgrade later.

**Device and version**
 - Device: samsung galaxy S6
 - Android version: Android 7.0
 - jtx Board version:  latest as of today
 - Downloaded from:  f-Droid

**Comment by patrickunterwegs** [comment]
Hey @afc54 , 
I'm really sorry for that!
The cause is not the sync, it's a bug in jtx Board. It only affects Android versions lower than 10, that's why I didn't realize it while testing. A user from Google Play wrote me and I uploaded a fix just within a day. I checked f-Droid and was glad, that it didn't pick up the broken version yet. I thought as the fixed version is there already, f-Droid would just skip the broken one and all is fine. However, now it seems like there is the broken one on f-Droid :-(  I don't know how that happened... but I have no control over the versions there and when they will update again. Usually it should happen within days, the fixed version is already there for four days now. 
Otherwise please take the version directly from GitHub, that should solve the problem immediately. 

Sorry once more, it's really bothering that there isn't more control over the versions on f-Droid...

**Comment by afc54** [comment]
Thanks for the quick reply!  I'll wait for a while for f-droid to get the fixed version.  If this doesn't happen relatively quickly I'll get the github version.  Thanks again.

**Comment by rogercreagh** [comment]
Actually this bug also affects Android 10. I've just updated my tablet with A10 from fdroid and it gave me 2.7.7 which gives an error on startup. Very annoying as you say above it only affects versions lower than 10.

Now stuck until fdroid catch up with 2.7.8. :-(

**Comment by patrickunterwegs** [comment]
Well, sorry again, as I said, I tried to be as quick as possible to get it fixed. But as I already have health issues due to high workload, the alternative is to not do any updates in the near future until things calm down for me.

**Comment by patrickunterwegs** [comment]
f-Droid is updated now. Sorry again for the issue!

**Comment by rogercreagh** [comment]
Appreciate the effort. Fdroid is obviously a bit of a pain for apps that are in active development. Unfortunately my main journal device is using the Fdroid build and I can't switch without uninstalling and risking loosing stuff (local items eg). Understand it is not your problem, just wish I'd used the apk from github option for that device from the start (although I think at the time the apk's weren't available on github hence starting with fdroid.
