### ISSUE TITLE
Recurring sub-tasks marked complete in future instances

### ISSUE THREAD

**Issue by cassava** [TechbeeAT/jtxBoard#1526]
**Describe the bug**
When marking sub-tasks of a recurring task as complete, they are also marked complete for future instances.
My expectation is that these are separate. Am I doing something wrong here?

**To Reproduce**
1. Create a new task A
2. Add one or more subtasks Aa, Ab, ...
3. Make task recurring, e.g. weekly -> A1, A2, ...
4. Save
5. In the task list, mark A1a as complete

**Expected behavior**
I expect A1a to be marked as complete, and A2a to remain open.
However, upon marking A1a complete, A2a is also updated.

**Device and version**
 - Device: Samsung Galaxy S10+
 - Android version: Android 12
 - jtx Board version: 2.09.00.gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @cassava , sorry for the late reply. 
This is not really a bug. The problem here is that the iCalendar standard that links subtasks through its UID. But recurring entries share the same UID and therefore subtasks are linked to ALL recurring entries. That's how it happens that when you edit one subtask, it is updated on all recurring entries (because they just link the same subtasks). 

I have added a warning for those cases in the app. The only way to solve the issue in your case is to unlink all instances from the series. This would actually create copies and remove the recurrence itself, so you can't update the whole series anymore, but the subtasks will also be copied, so that each (detached) instance would now get their own subtasks. 

I hope that explanation helps. But I can't offer anything else here as it would not comply with the standard.

**Comment by cassava** [comment]
Thanks @patrickunterwegs for the explanation. It helps to know this!
