### ISSUE TITLE
[Feature] allow markdown checkboxes clickable

### ISSUE THREAD

**Issue by MaDill** [TechbeeAT/jtxBoard#1636]
Before I was using https://github.com/dmfs/opentasks and there I used to create a shopping list. It was very easy to create an task with al lot of check boxes and set the mark when look at the task.

I created the task and the check boxes can be seen, but they can not checked. To show the check mark i have to open the task, navigate the cursor between the [ ], delete the white space and type an x.

During shopping this is not easy.

When the task is created and the task is in display view, it would be nice to be able to check the boxes.

**Your current device and version**
 - Device: Sony xperia 10, Lenovo Tab 8
 - Android version: Android 13
 - jtx Board version: 2.09.02
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hi @MaDill !
Thank you for your remark, I understand that OpenTasks had a different approach on subtasks, but that approach didn't fully support the standard. In jtx Board I wanted to make an app with a rather complete implementation of elements the standard offers. 
Markdown itself is not defined in the standard, I just did this basic implementation because of some demand. However, checkboxes are not supported, but I also don't want to change this. The thing is that you can easily create subtasks anyway (also through the top app bar), if I now start to support also checkboxes in the description of a task, this would contradict with the option to create actual linked subtasks. I think this would end up very confusing if those two approaches are mixed. 

I appreciate that you took the time to come back to me for such a feature request, but regrettably in this case I would refuse.
