### ISSUE TITLE
[BUG]  can't create new calendar with journal support in DAVX5

### ISSUE THREAD

**Issue by bobykvv** [TechbeeAT/jtxBoard#1680]
**To Reproduce**
1. Go to 'DAVx5'
2. Click on 'Create calendar' in CalDAV', put ticks on every possible calendar entry (Events, Tasks, Notes/Journal), click on 'Create calendar'
3. Calendar is created without Journal support, only calendar and tasks are available
4. After successful sync I see this new collection in jtx Board with Notes and Journal n/a.

**Device and version**
 - Device: Xiaomi MiNote 10T Pro
 - Android version: 12
 - jtx Board version: 2.09.03.ose
 - Downloaded from: f-Droid

![Screenshot_2024-12-22-22-45-22-779_at bitfire davdroid](https://github.com/user-attachments/assets/17eaa8fc-8204-4ce3-83fb-60d00a9e4628)

![Screenshot_2024-12-22-23-11-49-713_at techbee jtx](https://github.com/user-attachments/assets/630326cb-b047-4534-9c6b-0f4f1cfd377e)

**Comment by patrickunterwegs** [comment]
Hi @bobykvv , 
I'm afraid there is not much I can do here. DAVx5 just passes on the information it gets from the server. The problem is that some servers haven't properly implemented the standard. If you look at the compatibility list here: https://jtx.techbee.at/sync-with-davx5 You can see that I tested it with a couple of servers (or got feedback from users). However, some servers just behaved the way you described. Even though you choose VJOURNAL support, the server just ignores it and only supports VTODO. 
You could still check with DAVx5, but it is just very very likely that it's the server that has a problem (or an incomplete implementation of the standard). So the best thing you can do is contact them and see if they can do something about it.

**Comment by bobykvv** [comment]
Thank You for the answer, bit it's just strange, as it's my own nextcloud server (Nextcloud Pi OS), which worked just fine with jtx before I had to reinstall the OS.

**Comment by Seemseasy11** [comment]
> Thank You for the answer, bit it's just strange, as it's my own nextcloud server (Nextcloud Pi OS), which worked just fine with jtx before I had to reinstall the OS.

@bobykvv I had this issue on my nextcloud server as well, I think default new calendar doesn't enable VJOURNAL component and all I had to do was go in the Mariadb (or whichever database your using) and manually enable the VJOURNAL component for that specific calendar, restart Apache2 and then refresh list in DAVx5 and all the components showed up.
