### ISSUE TITLE
Sub tasks not visible on recurring journal entries 

### ISSUE THREAD

**Issue by DickinsonSa** [TechbeeAT/jtxBoard#233]
**Overview** :

The journal does not show the presence of sub tasks for recurring entries. There is then no way of knowing subtasks exist for a recurring entry. 

**Real world scenario** :

Car insurance due every year (journal entry) 
Sub tasks - 
     Search for a better company. 
     Arrange a deal and pay. 
     Put copy of certificate in car. 

**How to recreate** :

Create a journal entry.
Add a subtask.
Select 'show all options' then click 'recurrence'.
Select some frequency of recurrence.
Click 'save'.
View in any mode.

Perhaps I have not understood the best method for dealing with this scenario.

Device :
Huawei P20

**Comment by patrickunterwegs** [comment]
Hello @DickinsonSa , 
this feature was not implemented on purpose at the beginning, but it will be done in the upcoming larger version 2.3 (together with #190). 

Let me explain the difficulty: 
All entries have a unique UID. 
BUT recurring entries share the UID as long as they are not made an exception. 
Now any subtask is linked to its parent through the UID. When you consider now recurring entries with subtasks, a subtask would be linked to ALL recurring entries instead of only one instance. (This also mean when you mark a subtask as done, it is marked as done fall all recurring instances - because the subtask is the same, just linked to all of them).

In your case you want to create a recurring entry with the subtasks copied for each recurring instance. But this is not possible, at least not if you would like to stick to the iCalendar-standard.

Due to this complexity (it is also getting much more complex when you think of the synchronisation afterwards) I just reduced the functionality of the app to not link the subtasks when I started making this app. 

However, now I'm about to refactor this part and I will also implement a solution that allows both options (subtasks link to all instances and individual subtasks for recurring instances). 
When you create a recurring entry with subtasks, I will add the option to create all entries as exceptions for the case that there are subtasks. This would then be like creating multiple copies of the same entries with the given recurrence rule. 

So this is just an explanation why it's complicated and it takes a while (it should also be tested thoroughly) ;-)
For now I'd ask you for your patience until 2.3.0 is ready!

**Comment by DickinsonSa** [comment]
Hi Patrick, 
Thanks for the in-depth reply. It's a quandary: on the one hand you have recurring journal entries, on the other, tasks mixed in with them.
Just a thought, would it be easier (and cleaner) to keep the journal entries seperate and 'throw' those sub tasks into the tasks pot?
That would keep the functionality separate - journal / tasks.
This is perhaps my naive way of looking at things.
Good luck.

**Comment by patrickunterwegs** [comment]
Hey, well, not allowing the relation between journals and tasks wouldn't really make it better. After all the same problem would occur when you create a recurring task with subtasks 😉 
But don't worry, I'll figure something out for 2.3! When it's ready for beta, I'd appreciate your feedback!

**Comment by DickinsonSa** [comment]
Hi, yeah, I tried to create a journal entry in tasks the same with sub tasks - and realised its going to work just the same there!
I can wait. 
Thanks.
