### ISSUE TITLE
[BUG] markdown not applied in task list

### ISSUE THREAD

**Issue by xcy7e** [TechbeeAT/jtxBoard#24]
Hi @patrickunterwegs ,

I found an issue with the markdown formatting. When using in task description, it is working great inside the task detail view, but on the task list, the markdown formatting is not applied, but I see the formatting chars.
I'd assume this is a bug. 

e.g. 
`**foobar**-description` is being shown as **foobar**-description in the task view but as `**foobar**-description` in the task list.

On *task title* no markdown is applied at all but I assume that's per design and not a bug.

- all 4 task views affected (list, kanban,..)
- only tested two markdown formats: bold (`**`) & underline (`_`)

**Device and version:**
 - Device. Samsung Galaxy a51
 - jtx Board version: 2.01.01.rc12.gplay

**Comment by patrickunterwegs** [comment]
Hey @xcy7e !
Thanks for the ticket, but this was actually done on purpose, so the markdown is just not applied. 
The thing is that the lines are just meant as a preview. Applying markdown there comes with several problems: 
- the user could have used a heading that would be much bigger than all other texts and would probably look pretty ugly (if not cause some other layout issues), 
-  the description has an ellipsis at the end (that is done by the system automatically whereever the 6th line ends. If a start tag would be before the ellipsis but the end tag after, you would still see only the tag. In the worst case the start tag could be at the beginning of a newline and it could unintentionally be interpreted as a bullet point.
- the user could also embed images (available from 2.1.2), this would also not be very nice if images are present that cover a lot of space on the screen

I am open for discussion, but because of these points I would still not implement the markdown formatting in the list.

**Comment by xcy7e** [comment]
Hi Patrick,

thanks for your fast reply. I hear you and after my post I thought, well maybe that's intentionally, yeah.

Maybe it would help to remove markdown chars in the tasklist, to not have these "annoying formatting chars" there, (=plain text) but I see the amount of work and testing that would be required for all the different formatting rules. 

Alright then, sorry for bothering.

Have a good one!

**Comment by patrickunterwegs** [comment]
Hey, no worries, I'd rather have a discussion more than some "works as designed" that is just bothering. So thanks for the short discussion. 😉
Enjoy your weekend!
Cheers, Patrick

**Comment by patrickunterwegs** [comment]
One more thing: about the formatting tags I've created a feature request for the markdown library to offer a way to have a lower opacity for the tags to make them less bothering, that might also be nice to be applied in the list once it's done!
