### ISSUE TITLE
[Feature] Associate colors to categories

### ISSUE THREAD

**Issue by unalignedcoder** [TechbeeAT/jtxBoard#263]
Assume a user who routinely associates a category to their  entries, and at the same needs to color-code this categorization. 

Presently, it takes two different steps to do this.

The user might also have to consume extra attention time, in order to go back to double check that they are picking the right color for that categorization. 

When creating a new category, it would be neat if the user was given the option to pick a color associated to that category - thus having to do this only once, rather than each time.

**Comment by patrickunterwegs** [comment]
Hey, I will think about it but I cannot promise that this will be implemented. 

The problem is that there is no central registry for categories. The categories that are shown are an the aggregated categories of all entries. 

Making an extra color attribute for a category is possible, but every single category of every single entry needs to have this color attribute assigned. It is hard to impossible to keep this consistent as through the sync conflicts can occur at any time.

An alternative would be to allow the user to make some predefined categories with colors assigned and keep them in a central registry, but only for the app itself. When using jtx Board on another device, it must be set up the same way with the same categories and colors in the preset, to actually apply the colors.

I think both approaches are not really satisfying...

**Comment by unalignedcoder** [comment]
The second option is not so bad. 

I would see this feature not as extra information, rather as a visual reference.

It's okay that this is confined within the app. It's not something that should be saved in a webdav database, and thus would not be subject to sync conflicts. 
The category-color would only be there to visually aid the navigation within the app, while avoiding the user the task of coloring each entry individually. 

As for information, the category of each entry is saved: this suffices.

Should the user reinstall the app, they can take the time to re-associate categories to a color of choice.

**Comment by unalignedcoder** [comment]
Alternatively, or in addition, it would be really useful if the user could save their own custom "swatches" above the color pick, so that they don't have to guess-clicking the palette to replicate the color they have already used previously.
