### ISSUE TITLE
[BUG] Widget background color is out of sync

### ISSUE THREAD

**Issue by antonkravc** [TechbeeAT/jtxBoard#289]
**Describe the bug**
It seems that the background color of the widget gets out of sync when switching between system wide light and dark mode. The text color seems to be updated properly.

**To Reproduce**
- Place the widget
- Toggle dark mode
- Background should be incorrect
- Open and close the app
- Background should now be correct

**Expected behavior**
Background color should be updated when switching between system wide light and dark mode.

**Screenshots**
Screen recording
https://youtube.com/shorts/iBmhHGgyJAs

**Device and version:**
 - Device: Google Pixel 7 Pro
 - Android version: 13
 - jtx Board version: 2.02.01-rc11.gplay
 - Downloaded from: Google Play

**Comment by patrickunterwegs** [comment]
Hey @antonkravc , thanks for your issue report. 
Indeed I am aware of this issue and I have already investigated a bit. 
The problem is the widget library here. Because of the option to set the opacity of the widget colors, the colors need to be calculated when they change (and not just applied). This requires the widget to completely refresh (which it does when you bring the app to the background or when the sync with DAVx5 is running in the background). That's why the problem solves itself when you open and close the app. 
I will check again if I can find a way to get the app notified when the system setting for dark/light mode changes!

**Comment by antonkravc** [comment]
Thanks!

**Comment by patrickunterwegs** [comment]
Hey @antonkravc , so I have checked this, the problem is really that the app does not get notified when the color mode changes, so the app can't update the widget at that time. Colors can be updated immediately as long as they are not change (e.g. by setting an opacity).
The compromise would now be: 

- Change the code to the way that at least colors get updated when day/night changes and opacity was not set (i.e. set to maximum)
- Update the widget regularly like every 15 minutes so at the latest 15 minutes after the change the widget would get updated (currently the widget only gets updated when the content changes or when the app is closed). 15 minutes is the lowest period that is possible in the periodic worker (Android functionality) that is used by the app. 

I hope you can also live with this compromise!

I have also commented on one of several issues that were reported at Google: 
https://issuetracker.google.com/issues/214733441
But it was already open for a year and then just closed, I don't believe that they will provide a proper solution for this problem any time soon...
