### ISSUE TITLE
widget colors not refreshing when switching between light and dark theme

### ISSUE THREAD

**Issue by Dan2077** [TechbeeAT/jtxBoard#409]
![Screenshot_20230325-083505](https://user-images.githubusercontent.com/108411636/227765351-b06808ea-b848-485f-b3ac-bceaaa3e408e.png)
![Screenshot_20230325-083518](https://user-images.githubusercontent.com/108411636/227765490-ffdc902c-2ed1-4b4c-895f-9e94a4158ee0.png)
Colours correct themselves after opening and closing the widget

**Comment by patrickunterwegs** [comment]
Hey @Dan2077 , which version of jtx Board are you using?

**Comment by Dan2077** [comment]
Hey @patrickunterwegs , I'm using Version: 2.02.02-rc5.ose (202020005)

**Comment by patrickunterwegs** [comment]
Thanks @Dan2077 !
That issue was also addressed here: #289
In #289 I have added a change that if the opacity was not changed, the widget would update automatically. If the opacity was changed, the widget would only refresh itself after 10-15 min, regrettably there is a constraint in the system that doesn't allow a better solution. 
In v2.4.0 I will also add a dedicated note in the app for this problem (#286). 

#289 is included in v2.3.0, regrettably f-Droid has some issues with building apps lately (see also #404 and #393), so that fix is already available on Google Play, for f-Droid there is still a delay - but there's nothing I could do about it but ask for your patience 😉
