### ISSUE TITLE
[Idea] Beta channel on F-Droid

### ISSUE THREAD

**Issue by StefanoWoerner** [TechbeeAT/jtxBoard#434]
Quite a few people interested in FOSS development prefer installing apps through F-Droid. Since those FOSS-interested people are the most likely to give feedback, it may be worth it to consider adding a beta channel to F-Droid.

I have no idea how much effort maintaining an additional F-Droid package is and if it would be really worth it. Just wanted to put this idea out there.

**Comment by patrickunterwegs** [comment]
Hey, so basically an app has a package name which acts as an identifier for the OS and appstores. That's why you might see the same app in multiple different stores as installed. 
f-Droid does not have a beta channel (unlike Google Play), so the only way to offer betas on f-Droid would be by providing either all versions, independent of beta status or not, or to make a version with a dedicated package name, which would be like another app that needs to be considered in DAVx5 as well. Both ways are just workarounds for the incapability of f-Droid to provide a beta channel. 

In my opinion this is something that should be addressed and solved on f-Droid side. Everything else would just be a workaround...
