### ISSUE TITLE
[BUG] v2.1.2 Sort Date Descending not working

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#50]
Upgrading from 2.1.1 to 2.1.2 the sort order for journal lists (compact and full) resets itself to Date Ascending (ie oldest at top) and can't be changed.

No other filter or group is set but changing the date order from ascending to descending does nothing.

A bit urgent if you like to work with the newest entry at the top of the list.

(I see group and order now share a single tab - perhaps  something got lost in combining them)

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , thank you!
Indeed, that's a bit strange, I just reproduced it. I will have a look at that tonight 👍

**Comment by patrickunterwegs** [comment]
Thanks again @rogercreagh , I found the cause and fixed it. It had to do with the group by options. Some time ago I also added the group by status and classification options, those needed some special handling for the sort order which caused a bug also in the other sort orders. 

Until the fix is published, you can order by any value, that you maybe don't use frequently (e.g. Classification) and then set the second sort order to the date/descending.
