### ISSUE TITLE
[BUG] Changing collection when editing a Journal causes exit to list or crash

### ISSUE THREAD

**Issue by rogercreagh** [TechbeeAT/jtxBoard#505]
**Describe the bug**
Create a new journal item and immediately change the collection (first box). It crashes out to the list or exits jtxB completely leaving a blank entry for the date in the correct collection.
Sometimes it will also leave a blank entry in the originally selected collection.
It also happens if you change the date first and then change the collection.

**To Reproduce**
Steps to reproduce the behaviour:
As above

**Expected behaviour**
The collection should be changed and the edit screen remain allowing editing to continue. If an item has been created in the background in the default (previously selected) collection it should be deleted.

**Screenshots**
n/a 

**Device and version:**
 - Device: Boox
 - Android version Android 11
 - jtx Board version:2.3.1
 - Downloaded from:  f-Droid,

**Comment by patrickunterwegs** [comment]
Hey @rogercreagh , 
thanks, it's weird that this doesn't happen on every device and also not every time. 

However, I hope I found the root-cause and fix. 
(Here's a reminder to myself: https://stackoverflow.com/questions/59491707/how-to-wait-for-end-of-a-coroutine)

At this point I have also changed how it works, so moving an entry to a new collection would now refresh the current screen instead of moving to another screen with the copied data (in the new collection).
