### ISSUE TITLE
[BUG] Release at F-Droid are all release candidate versions

### ISSUE THREAD

**Issue by BaumiCoder** [TechbeeAT/jtxBoard#522]
**Describe the bug**
All versions on F-Droid are rc version (release candidate) . At some app stores (like [App Lounge from /e/OS](https://gitlab.e.foundation/e/backlog/-/issues/6869#note_379516)) this triggers, that this versions are not available there. They only want to provide release version and not release candiates, betas or something like this.

**To Reproduce**
1. Start App Lounge on an /e/OS device.
2. Install jtx board from there.

**Expected behavior**
I have the newest version of jtx board (available at F-Droid) on my device.

**Current behavior**
I only gets the oldes version of jtx board, that is available at F-Droid.

**Device and version:**
 - Device: Fairphone 4
 - Android version [e.g. Android 11]
 - jtx Board version: 1.00.15-rc01.ose (100150001)
 - Downloaded from: App Lounge (which gets it from F-Droid)

**Comment by patrickunterwegs** [comment]
Hey @BaumiCoder ,
Thanks!
In fact in the last year I was just using the latest stable release candidate and I never updated the version number, there was actually no need as Google Play has some manual steps and f-Droid take the version according to the tag of the commit. As long as the tag doesn't contain -beta or -rc, f-Droid would take it. So I do update the tag, but not the version code itself.

I can also update the version code in the future, but I think it would be better if /e/ would just take the latest version from f-Droid anyway instead of implementing their own logic...

**Comment by patrickunterwegs** [comment]
I published the new versio now without the -rc postfix.

**Comment by BaumiCoder** [comment]
Thanks, the new release is fetched by the App Lounge.
This own logic there is maybe necessary, because the user can't chose a version of the app in App Lounge. They have introduced it with this issue [here](https://gitlab.e.foundation/e/backlog/-/issues/5279). Furthermore App Lounge uses difference sources for the apps, not only F-Droid repositories.

**Comment by patrickunterwegs** [comment]
Thank you for the update! I'm glad it resolved now :-)
