### ISSUE TITLE
[BUG] Sync triggered conflicing with 'manual only' in DAVx5

### ISSUE THREAD

**Issue by amonrid** [TechbeeAT/jtxBoard#576]
**Describe the bug**
jtx Board triggers a DAVx5 sync each time a change occurs locally, which is undesired as the properties of the DAVx5 account are set to sync only manually. Given the Cal/CardDAV server is not publicly reachable, this results in a continuous stream of notifies about the failures. 

This might be related (i.e. influenced by) to the new sync. mechanism that DAVx5 introduced in version [v4.3-ose](https://github.com/bitfireAT/davx5-ose/releases/tag/v4.3-ose) but unsure about the timings of first occurrence and its relation to the release/upgrade timings.

**To Reproduce**
1. Open jtx Board 
2. Make any change or accidentally 'pull down'
3. jtx Board will show the 'busy syncing' bar, as will DAVx5, shortly after failing (unless the server is reachable)

Potential relevant: errors persist, perhaps showing or using the widgets triggers it as well. 

**Expected behavior**
"Only sync manually" configuration in DAVx5 is honored. 

**Screenshots**

**Device and version:**
 - Device: Samsung Galaxy S22
 - Android version: Android 13
 - jtx Board version: 2.04.02.gplay
 - Downloaded from: Google Play
 - DAVx5 version: 4.3.2-gplay

**Comment by patrickunterwegs** [comment]
Hi @amonrid , in fact this setting is just not considered in jtx Board (but I assume it's also not considered in Tasks and OpenTasks.
@rfc2822 @devvv4ever how would you handle this?

**Comment by devvv4ever** [comment]
AFAIK this is indeed a problem with the type of sync an app requests. If it calls a sync with highest priority it is just as the user would press the sync button manually in DAVx5. Pressing this button ignores all settings and performes a sync regardless of almost any settings.

We thought about that already and in the future we could introduce an additional sync restriction option that is based on "network / connection type". So if you then set that DAVx5 should only sync when connected to a WiFi it will absolutely only make the sync when it is connected to this network. Right now we still use the Android Sync Framework, where we don't have enough control over the sync.

This functionality can only be developed when we get more control of the sync into DAVx5 itself with the WorkManager instead of  using the Android Sync Framework. The good thing: After many many months of coding and re-working the core of DAVx5 this version is almost ready (currently in beta) and will hopefully be released next week. This will be the foundation of many other features such as the one I described above:

* Sync based on "Network/Connection Type"
* as well as the possibility to sync without internet connection in only a LAN (limited by a Internet connectivity check of the Sync Framework)
* syncing even when storage space is low (currently stops sync even if there is enough space)

**Comment by patrickunterwegs** [comment]
Yes, in fact jtx Board requests a sync every time you open the app with the Expedite flag. (This way you always get the latest data fetched when you look at your list) 
Even in the future it might be difficult to find out if a sync is desired by a user or not. 
Another option could be to add some setting in jtx Board. But then you'd need to set the setting twice, once for jtx Board, once for DAVx5...

**Comment by patrickunterwegs** [comment]
As a solution for this problem I will add two settings to make the sync on start optional and the sync on swipe refresh optional. Once you deactivate those options, DAVx5 will only be notified about a change and the DAVx5 settings will apply. There will still be the option to trigger a sync manually through the menus.

**Comment by amonrid** [comment]
@patrickunterwegs, thank you very much!
