### ISSUE TITLE
the 'return key' does not submit in an edit popup

### ISSUE THREAD

**Issue by mynameisflorian** [TechbeeAT/jtxBoard#594]
In an edit popup (such as is found when you try to save a filter preset) inserts a newline instead of submitting when you hit the enter key This givea the appearance that the value was cleared but the popup remaines in place. my expectation is that the popup either expands it's height to accommodate a second line, or submits the value.

Thank you,
Florianll

Imo

**Comment by patrickunterwegs** [comment]
Hey @mynameisflorian , 
thanks, indeed for saving the filter presets it makes sense to immediately save instead of allowing a line break. 
I reviewed also other spots, but I think in other cases it's still better to allow a line break. If you encounter any other spots where you think it makes sense to save immediately, just let me know! :-)

**Comment by mynameisflorian** [comment]
I would think in all cases it should submit immediately. On my screen with my settings, entering a new line completely hides the previous line so it's not clear what is going on. It looks like the box was cleared out. As an alternative perhaps the text input box could become a 2 line (or 1.5 line?) entry box when there is more than one line so that you can see that the previous line is still there?

May 25, 2023 01:38:25 Patrick Lang ***@***.***>:

**Comment by patrickunterwegs** [comment]
Other places are like when you edit a subtask or a subnote. If the soft-keyboard action is set to "Done", then you don't have any possiblity to add a line break which would also not be desirable.
