### ISSUE TITLE
[BUG] mystery status NO_STATUS not visible in kanban

### ISSUE THREAD

**Issue by AeliusSaionji** [TechbeeAT/jtxBoard#637]
**Describe the bug**
I have no idea how this happened, but a number of my entries are status: NO_STATUS

This creates one oddity and one problem:
Oddity: A status label NO_STATUS is shown.
Problem: NO_STATUS tasks do not appear in Kanban view, but they do appear in all other views.

Bulk editing to set status to cancelled, then back to "No status" did not work; they still have the status NO_STATUS.

Are your eyes crossed yet? :P

**Screenshots**
![Screenshot-2023-06-19-17-09-04_llcrop](https://github.com/TechbeeAT/jtxBoard/assets/4342746/4f6e1032-3e22-4b08-9724-17f7175295a8)

**Device and version:**
 - Device: Sony Xperia 1 IV
 - Android version: 13
 - jtx Board version: 2.04.05 ose
 - Downloaded from: github

thanks!

**Comment by patrickunterwegs** [comment]
Hey @AeliusSaionji , indeed I'm feeling a bit like that 😵 
So the problem is the bulk update functionality in combination with the "No status" option, instead of setting it in the database to "NULL", the value is set to the technical (internal) value that should only be used in the code. I'll have a close look soon, I mean, I just did, but it takes a bit more time to get resolved properly.

But thanks for your bug reports by the way 😉
