### ISSUE TITLE
[Feature] Indicator for sync activity between jtx Board and DAVx⁵

### ISSUE THREAD

**Issue by Hawk777** [TechbeeAT/jtxBoard#659]
**Is your feature request related to a problem? Please describe.**
If I mark a task as completed in jtx Board then immediately start a DAVx⁵ sync, the completed task is *not* modified on the server (I run my own server, so I can see there are no `PUT` requests in the sync traffic). If I wait a minute or two and then start the DAVx⁵ sync, the completed task *is* modified on the server. So it seems there is some kind of eventual consistency going on *between* jtx Board and DAVx⁵, but there’s no visual indication of when this synchronization is happening or when it has finished. This lack of indication made me think that jtx Board was broken at one point, because it was still showing a task I had marked as complete on my computer, synced up to my server, and *supposedly* synced down to my phone in DAVx⁵—but I assume it the change was probably just not migrated from DAVx⁵ to jtx Board yet.

**Describe the solution you'd like**
Some kind of indicator that jtx Board is sending data to or receiving data from DAVx⁵ would tell me when I should expect everything to have reached consistency.

**Describe alternatives you've considered**
Another option would be to completely eliminate the delay by making the accesses synchronous, but I assume that would make jtx Board too slow for interactive use.

**Comment by patrickunterwegs** [comment]
Hi @Hawk777 , 
The problem here is actually DAVx5, for various reasons they have switched from the Android sync framework to the work managers. While the sync manager was indicating the ongoing sync for other apps, the work managers doesn't allow such a query by other apps. 
A workaround was to artificially keep a sync manager session open so that other apps get notified. It seems like this doesn't really work reliably.

I will talk with them what's their current approach.
But basically within jtx Board there's nothing that can be done. DAVx5 should either provide an alternative way to check if the sync is ongoing or to reliably keep the sync manager blocked until it's done. By the way this is a problem for any app that uses DAVx5 and relies on the sync manager (like calendar or contact apps might do).

**Comment by Hawk777** [comment]
Oh OK, thanks for passing it on.

**Comment by patrickunterwegs** [comment]
Hey @Hawk777 
So I had a small misunderstanding, the problem was fixed in DAVx5 but just not released, it will come in DAVx5 4.3.5 which should be released within the next two weeks =)
So I'm closing this issue now as it's solved there.
