### ISSUE TITLE
[BUG] Italian translation 

### ISSUE THREAD

**Issue by dado70** [TechbeeAT/jtxBoard#745]
Hi,
using italian language the label in  buttons "cancel" and "dismiss" are the same ("annulla") instead of: "elimina" "annulla"

![IMG_20230805_090352](https://github.com/TechbeeAT/jtxBoard/assets/109067755/a79d41cd-ed36-4cf9-a167-b39a29e9f35e)
![IMG_20230805_090326](https://github.com/TechbeeAT/jtxBoard/assets/109067755/4567cbdf-c243-4e1a-8e30-cda937e680fd)

**Device and version:**
 - Device: [Xiaomi mi 10 lite 5g]
 - Android version [Android 11]
 - jtx Board version: [2.05.01.ose (205010012)]
 - Downloaded from: [Google Play, f-Droid.]

**Comment by patrickunterwegs** [comment]
Hey @dado70 !
Thank you for your bug report!

Basically if you're interested you can also join the translation project and correct or add missing translations yourself =)
https://crowdin.com/project/jtx-board/invite?h=a8fd45e2dfea25534eda503b441476ea1545967

About this specific problem: 
I will correct it, but it's a bit tricky. There are two combinations for the buttons: Cancel + Delete and Cancel + Discard.
Now the problem is the translation uses the same word for discard (annulla) and cancel (annulla). I do speak a bit of italian, but those details are too much for me 😉  can you tell what would be the best words to say discard, cancel and delete?

**Comment by patrickunterwegs** [comment]
@dado70 , I'm taking "scatta" now for discard, also in other sentences. If you feel like you can find a better fit, please join the translation project and update the strings directly =)

**Comment by patrickunterwegs** [comment]
Done in ee9fca68ea611d56101b535bb35afbd3dc0e03c6
