### ISSUE TITLE
[BUG] Use locale-dependant Decimal Separator for GEO properties

### ISSUE THREAD

**Issue by dilyanpalauzov** [TechbeeAT/jtxBoard#964]
In jtxBoard 2.06.00 when my system uses the German locale and jtxBoard shows GEO coordinates, it uses fullstop to as Decimal Separator.  Correct will be, based on the current locale, to use comma.

![Screenshot_20231020_205114](https://github.com/TechbeeAT/jtxBoard/assets/4992947/614c79dd-0ff3-4e71-aa79-da420441e168)

**Comment by patrickunterwegs** [comment]
Hi @dilyanpalauzov , actually I did this on purpose because I thought it looks a bit strange when the values are also separated by a comma: 
<img width="441" alt="Bildschirm­foto 2023-10-20 um 22 24 36" src="https://github.com/TechbeeAT/jtxBoard/assets/72232737/61361a1e-bfdd-423f-9818-efb9b5c110f3">

I can do the change, but do you really think it's better like that?

**Comment by dilyanpalauzov** [comment]
As I mentioned elsewhere, I do not think that the values LAT and LON shall be separated by comma.  This presentation: φ54,36428 λ18,65731 can use locale dependant Decimal Separator without problem.
