### ISSUE TITLE
[BUG] Existing Notifications do not hide in 'do not disturb' mode

### ISSUE THREAD

**Issue by graue70** [TechbeeAT/jtxBoard#991]
**Describe the bug**
When I have notifications from jtx alarms and I activate the 'do not disturb' mode of Android, the notifications disappear for a split second and then immediately come back.

I didn't try what happens with new notifications during activated 'do not disturb mode'.

**To Reproduce**
Steps to reproduce the behavior: See above

**Expected behavior**
When I activate the 'do not disturb mode', all notifications of all apps should be hidden.

**Device and version:**
 - Device: Samsung Galaxy S10
 - Android version: Android 13
 - jtx Board version: 2.6.1
 - Downloaded from: f-Droid

**Comment by patrickunterwegs** [comment]
Hi @graue70 , I don't see a way how an app can have more influence on how Android handles notification except by the priority of the notification channel. So alarms in jtx Board have a dedicated notification channel which has an attribute for the priority. The priority for jtx Board is set to MAX. This is necessary to make sure that alarms are triggered on time (and not delayed by power saving or any other setting). Additionally you can enable full-screen alarms which also need a high importance in the notification channel in order to be shown as such (as otherwise Android would downgrade them to a normal notification).

So I don't see downgrading the importance of jtx Board as an option and also no alternative to influence this behaviour and I would close this issue.

**Comment by graue70** [comment]
Hmm. Interesting. I read throgh [the docs](https://developer.android.com/develop/ui/views/notifications#dnd-mode) but didn't learn much.

By priority (MAX), do you mean the importance (URGENT)?

I have the setting configured like this:

<img src="https://github.com/TechbeeAT/jtxBoard/assets/23035329/99d40c2f-b255-4a27-bca0-111a7bc8935f" height="600" />

It seems to be pretty clearly saying that NO notifications are visible. That still makes me think that there is something misconfigured in jtx.

Also, I can specifically go to the notifications manager settings and specify that jtx alarms can ignore the 'do not disturb' mode but I can't specify the opposite.

**Comment by patrickunterwegs** [comment]
Hm, the notification channels are described here:
https://developer.android.com/develop/ui/views/notifications/channels#importance

I still don't see how the app could be configured differently. I can try later to check if the app even gets notified when you switch to Do not disturb, but I really doubt it, it shouldn't be the apps responsibility to handle open notifications for a change of such a setting...

**Comment by graue70** [comment]
The [docs for `NotificationManager`](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_MAX) seem to say that `IMPORTANCE_MAX` is unused. Also, the table you linked doesn't even mention `IMPORTANCE_MAX`. (There are four levels.)
However, the [docs for `NotificationManagerCompat`](https://developer.android.com/reference/androidx/core/app/NotificationManagerCompat#IMPORTANCE_MAX()) mention `IMPORTANCE_MAX` (there are five levels) and say that only this level allows full-screen notifications.
I just realized there is also [`NotificationCompat`](https://developer.android.com/reference/androidx/core/app/NotificationCompat#PRIORITY_MAX()) which has five levels including `PRIORITY_MAX`.

This is all very confusing to me. You're sure that if you used `NotificationManagerCompat.IMPORTANCE_HIGH`, full screen notifications wouldn't work, right?

Another similar app seems to use `NotificationManager.IMPORTANCE_HIGH` ([see the code](https://github.com/tasks/tasks/blob/0b87a206fef5c9fcbcd522592c92eb32e9543ec2/app/src/main/java/org/tasks/scheduling/NotificationSchedulerIntentService.kt#L55)).

Sidenote: To me, the jtx notifications are more reminders than they are alarms but I realize that might be subjective.

**Comment by ky-tt** [comment]
> I didn't try what happens with new notifications during activated 'do not disturb mode'.

I did - involuntarily. Although this issue is already closed with `wontfix` I mention my surprise that the jtx Board alerts do not honor `Do Not Disturb`.

> Another similar app seems to use `NotificationManager.IMPORTANCE_HIGH` ([see the code](https://github.com/tasks/tasks/blob/0b87a206fef5c9fcbcd522592c92eb32e9543ec2/app/src/main/java/org/tasks/scheduling/NotificationSchedulerIntentService.kt#L55)).
> 
> Sidenote: To me, the jtx notifications are more reminders than they are alarms but I realize that might be subjective.

Same for me: So far I used notifications for tasks as reminders and not like an "alarm clock" (reference to https://github.com/TechbeeAT/jtxBoard/issues/809#issuecomment-1690568587).

Is there a way for me to ask jtx Board to remind me of tasks while still honoring `Do Not Disturb`?

The "Another similar app" mentioned and linked by @graue70 behaves as expected, honoring `Do Not Disturb` and removing notifications automatically when e.g. a due date is moved.

I really appreciate the integration of jtx Board with DAVx5, so it would be great to have at least the option of lower priority notifications.
